### PR TITLE
switch to hashicorp terraform action

### PR DESCRIPTION
**Pull request by wderezin**

### CODE REVIEW

**Comment by wderezin** [comment]
@ksgriggs What do you think of the using the hashicorp terraform action vs dflock.  Could wrap the terraform commands up into a script.

**Review by ksgriggs — COMMENTED** [review]
The Hashicorp javascript action would be much quicker I believe.  I couldn't get it to take a terraform directory environment variable but it looks like you may have solved that.  Good job.

**Review by ksgriggs — APPROVED** [review]
I forgot to hit the approve button.

**Review by ksgriggs — APPROVED** [review]
Nicely done.

**Pull request merged**
